apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vitalam-ipfs.fullname" . }}-config
  labels:
    {{- include "vitalam-ipfs.labels" . | nindent 4 }}
data:
  healthCheckPort: {{ .Values.config.healthCheckPort | quote }}
  logLevel: {{ .Values.config.logLevel }}
  {{- if .Values.config.nodeHost }}
  nodeHost: {{ .Values.config.nodeHost }}
  {{- end }}
  {{- if .Values.config.nodePort }}
  nodePort: {{ .Values.config.nodePort }}
  {{- end }}
  ipfsCommand: {{ .Values.config.ipfsCommand }}
  ipfsLogLevel: {{ .Values.config.ipfsLogLevel }}
  ipfsArgs: {{ .Values.config.ipfsArgs | toJson | quote }}
  ipfsApiPort: {{ .Values.config.ipfsApiPort | quote }}
  ipfsSwarmPort: {{ .Values.config.ipfsSwarmPort | quote }}
  dataVolumeSize: {{ .Values.storage.dataVolumeSize | quote }}
