apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vitalam-ipfs.fullname" . }}-config
  labels:
    {{- include "vitalam-ipfs.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
