version: '3'
services:
  vitalam-node:
    image: ghcr.io/digicatapult/vitalam-node:v2.9.3
    command: 
      --base-path /data/ 
      --dev
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    restart: on-failure
